# TOML configuration file defining parameters for atmospheric and climate fields
name = "Atmosphere / Climate Fields General Info"
version = "0.3.0"
#  0.3.0   -add additional field: units_alt
date = "16 July 2024"

[flds]
  [flds.albsn]
    standard_name = 'surface_albedo'
    long_name = 'Snow Albedo'
    units = '1'
    units_alt = '1'
    type = 'sfc_state'
  [flds.cl]
    standard_name = 'cloud_area_fraction_in_atmosphere_layer'
    long_name = 'Cloud Cover'
    units = '1'
    units_alt = '1'
    type = 'pl_clouds'
  [flds.clbz]
    standard_name = 'height_at_cloud_base'
    long_name = 'Cloud Base Height'
    units = 'm'
    type = 'clouds'
  [flds.clh]
    standard_name = 'high_type_cloud_area_fraction'
    long_name = 'High Cloud Cover'
    units = '1'
    units_alt = '1'
    type = 'clouds'
  [flds.cli]
    standard_name = 'mass_fraction_of_cloud_ice_in_air'
    long_name = 'Mass Fraction of Cloud Ice'
    units = 'kg kg-1'
    units_alt = 'kg kg-1'
    type = 'pl_clouds'
  [flds.clivi]
    standard_name = 'atmosphere_mass_content_of_cloud_ice'
    long_name = 'Total Column Ice Water'
    units = 'kg m-2'
    units_alt = 'kg m-2'
    type = 'clouds'
  [flds.cll]
    standard_name = 'low_type_cloud_area_fraction'
    long_name = 'Low Cloud Cover'
    units = '1'
    units_alt = '1'
    type = 'clouds'
  [flds.clm]
    standard_name = 'medium_type_cloud_area_fraction'
    long_name = 'Medium Cloud Cover'
    units = '1'
    units_alt = '1'
    type = 'clouds'
  [flds.clr]
    standard_name = 'mass_fraction_of_liquid_precipitation_in_air'
    long_name = 'Mass Fraction of Rain Water'
    units = 'kg kg-1'
    units_alt = 'kg kg-1'
    type = 'pl_clouds'
  [flds.cls]
    standard_name = 'mass_fraction_of_snow_in_air'
    long_name = 'Mass Fraction of Snow'
    units = 'kg kg-1'
    units_alt = 'kg kg-1'
    type = 'pl_clouds'
  [flds.clt]
    standard_name = 'cloud_area_fraction'
    long_name = 'Total Cloud Cover'
    units = '1'
    units_alt = '1'
    type = 'clouds'
  [flds.clw]
    standard_name = 'mass_fraction_of_cloud_liquid_water_in_air'
    long_name = 'Mass Fraction of Cloud Liquid Water'
    units = 'kg kg-1'
    units_alt = 'kg kg-1'
    type = 'pl_clouds'
  [flds.clwvi]
    standard_name = 'atmosphere_mass_content_of_cloud_liquid_water'
    long_name = 'Total Column Liquid Water'
    units = 'kg m-2'
    units_alt = 'kg m-2'
    type = 'clouds'
  [flds.div]
    standard_name = 'divergence_of_wind'
    long_name = 'Divergence of Wind'
    units = 's-1'
    units_alt = 's-1'
    type = 'pl_dyn'
  [flds.evspsbl]
    standard_name = 'water_evapotranspiration_flux'
    long_name = 'Evaporation Including Sublimation and Transpiration'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.evspsblpot]
    standard_name = 'water_potential_evaporation_flux'
    long_name = 'Potential Evapotranspiration'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.frvel]
    standard_name = 'friction_velocity_in_air'
    long_name = 'Friction Velocity'
    units = 'm s-1'
    type = 'sfc_pbl'
  [flds.hfls]
    standard_name = 'surface_upward_latent_heat_flux'
    long_name = 'Surface Latent Heat Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.hfss]
    standard_name = 'surface_upward_sensible_heat_flux'
    long_name = 'Surface Sensible Heat Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.hur]
    standard_name = 'relative_humidity'
    long_name = 'Relative Humidity'
    units = '1'
    units_alt = '1'
    type = 'pl_met'
  [flds.hus]
    standard_name = 'specific_humidity'
    long_name = 'Specific Humidity'
    units = 'kg kg-1'
    units_alt = 'kg kg-1'
    type = 'pl_met'
  [flds.mrro]
    standard_name = 'runoff_flux'
    long_name = 'Total Runoff Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.mrrob]
    standard_name = 'subsurface_runoff_flux'
    long_name = 'Subsruface Runoff Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.mrros]
    standard_name = 'surface_runoff_flux'
    long_name = 'Surface Runoff Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.orog]
    standard_name = 'surface_altitude'
    long_name = 'Surface Altitude'
    units = 'm'
    units_alt = 'm'
    type = 'inv'
  [flds.pr]
    standard_name = 'precipitation_flux'
    long_name = 'Precipitation Flux (total)'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = 'precip'
  [flds.prc]
    standard_name = 'convective_precipitation_flux'
    long_name = 'Convective Precipitation Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = 'precip'
  [flds.prcprof]
    standard_name = 'convective_rainfall_flux'
    long_name = 'Convective Rainfall Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.prlsns]
    standard_name = 'stratiform_snowfall_flux'
    long_name = 'Stratiform Snowfall Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = 'precip'
  [flds.prlsprof]
    standard_name = 'stratiform_rainfall_flux'
    long_name = 'Stratiform Rainfall Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.prs]
    standard_name = 'stratiform_precipitation_flux'
    long_name = 'Stratiform Precipitation Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = 'precip'
  [flds.prsn ]
    standard_name = 'snowfall_flux'
    long_name = 'Snowfall Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = 'precip'
  [flds.prsnc]
    standard_name = 'convective_snowfall_flux'
    long_name = 'Convective Snowfall Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = 'precip'
  [flds.prw]
    standard_name = 'atmosphere_mass_content_of_water_vapor'
    long_name = 'Total Column Water Vapor (PWAT)'
    units = 'kg m-2'
    units_alt = 'kg m-2'
    type = 'clouds'
  [flds.ps]
    standard_name = 'surface_air_pressure'
    long_name = 'Air Pressure at the Surface'
    units = 'Pa'
    units_alt = 'hPa'
    type = 'sfc_met'
  [flds.psl]
    standard_name = 'air_pressure_at_mean_sea_level'
    long_name = 'Air Pressure at Sea Level'
    units = 'Pa'
    units_alt = 'hPa'
    type = 'sfc_met'
  [flds.rlds]
    standard_name = 'surface_downwelling_longwave_flux_in_air'
    long_name = 'Surface Downwelling Longwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.rldscs]
    standard_name = 'surface_downwelling_longwave_flux_in_air_assuming_clear_sky'
    long_name = 'Surface Downwelling Clear-Sky Longwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.rls]
    standard_name = 'surface_net_downward_longwave_flux'
    long_name = 'Surface Net Longwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.rlscs]
    standard_name = 'surface_net_downward_longwave_flux_assuming_clear_sky'
    long_name = 'Surface Net Clear-Sky Longwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.rlt]
    standard_name = 'toa_net_downward_longwave_flux'
    long_name = 'TOA Net Longwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'top_flux'
  [flds.rltcs]
    standard_name = 'toa_net_downward_longwave_flux_assuming_clear_sky'
    long_name = 'TOA Net Clear-Sky Longwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'top_flux'
  [flds.rsds]
    standard_name = 'surface_downwelling_shortwave_flux_in_air'
    long_name = 'Surface Downwelling Shortwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.rsdscs]
    standard_name = 'surface_downwelling_shortwave_flux_in_air_assuming_clear_sky'
    long_name = 'Surface Downwelling Clear-Sky Shortwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.rsdt]
    standard_name = 'toa_incoming_shortwave_flux'
    long_name = 'TOA Incident Shortwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'top_flux'
  [flds.rss]
    standard_name = 'surface_net_downward_shortwave_flux'
    long_name = 'Surface Net Shortwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.rsscs]
    standard_name = 'surface_net_downward_shortwave_flux_assuming_clear_sky'
    long_name = 'Surface Net Clear-Sky Shortwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'sfc_flux'
  [flds.rst]
    standard_name = 'toa_net_downward_shortwave_flux'
    long_name = 'TOA Net Shortwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'top_flux'
  [flds.rstcs]
    standard_name = 'toa_net_downward_shortwave_flux_assuming_clear_sky'
    long_name = 'TOA Net Clear-Sky Shortwave Radiation Flux'
    units = 'W m-2'
    units_alt = 'W m-2'
    type = 'top_flux'
  [flds.rv]
    standard_name = 'atmosphere_upward_relative_vorticity'
    long_name = 'Relative Vorticity'
    units = 's-1'
    units_alt = 's-1'
    type = 'pl_dyn'
  [flds.sbl]
    standard_name = 'surface_snow_and_ice_sublimation_flux'
    long_name = 'Surface Snow and Ice Sublimation Flux'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.sfcWdir]
    standard_name = 'wind_from_direction'
    long_name = 'Wind Direction at 10 m'
    units = 'degree'
    units_alt = 'degree'
    type = 'sfc_met'
  [flds.sfcWind]
    standard_name = 'wind_speed'
    long_name = 'Wind Speed at 10 m'
    units = 'm s-1'
    units_alt = 'm s-1'
    type = 'sfc_met'
  [flds.sftlf]
    standard_name = 'land_area_fraction'
    long_name = 'Land Area Fraction'
    units = '1'
    units_alt = '1'
    type = 'inv'
  [flds.siconc]
    standard_name = 'sea_ice_area_fraction'
    long_name = 'Sea Ice Area Fraction'
    units = '1'
    units_alt = '1'
    type = 'sfc_state'
  [flds.snd]
    standard_name = 'surface_snow_thickness'
    long_name = 'Snow Depth'
    units = 'm'
    units_alt = 'm'
    type = 'sfc_state'
  [flds.snm]
    standard_name = 'surface_snow_and_ice_melt_flux'
    long_name = 'Surface Snowmelt Flux (Ice + Snow)'
    units = 'kg m-2 s-1'
    units_alt = 'kg m-2 s-1'
    type = ''
  [flds.ta]
    standard_name = 'air_temperature'
    long_name = 'Temperature'
    units = 'K'
    units_alt = 'degC'
    type = 'pl_met'
  [flds.tas]
    standard_name = 'air_temperature'
    long_name = 'Temperature at 2 m'
    units = 'K'
    units_alt = 'degC'
    type = 'sfc_met'
  [flds.tauu]
    standard_name = 'surface_downward_eastward_stress'
    long_name = 'Surface Downward Northward Wind Stress'
    units = 'N m-2'
    units_alt = 'N m-2'
    type = 'sfc_pbl'
  [flds.tauu_an]
    standard_name = 'surface_downward_eastward_stress'
    long_name = 'Surface Downward Northward Wind Stress'
    units = 'N m-2'
    units_alt = 'N m-2'
    type = 'sfc_pbl'
  [flds.tauv]
    standard_name = 'surface_downward_northward_stress'
    long_name = 'Surface Downward Eastward Wind Stress'
    units = 'N m-2'
    units_alt = 'N m-2'
    type = 'sfc_pbl'
  [flds.tauv_an]
    standard_name = 'surface_downward_northward_stress'
    long_name = 'Surface Downward Eastward Wind Stress'
    units = 'N m-2'
    units_alt = 'N m-2'
    type = 'sfc_pbl'
  [flds.tcw]
    standard_name = 'atmosphere_mass_content_of_water'
    long_name = 'Total Column Water (all phases)'
    units = 'kg m-2'
    units_alt = 'kg m-2'
    type = 'clouds'
  [flds.tcwi]
    standard_name = 'atmosphere_mass_content_of_snow'
    long_name = 'Total Column Snow Water'
    units = 'kg m-2'
    units_alt = 'kg m-2'
    type = 'clouds'
  [flds.tcwr]
    standard_name = 'atmosphere_mass_content_of_liquid_precipitation'
    long_name = 'Total Column Rain Water'
    units = 'kg m-2'
    units_alt = 'kg m-2'
    type = 'clouds'
  [flds.tdps]
    standard_name = 'dew_point_temperature'
    long_name = 'Dewpoint Temperature  at 2 m'
    units = 'K'
    units_alt = 'degC'
    type = 'sfc_met'
  [flds.tos]
    standard_name = 'sea_surface_temperature'
    long_name = 'Sea Surface Temperature'
    units = 'K'
    units_alt = 'degC'
    type = 'sfc_state'
  [flds.ts ]
    standard_name = 'surface_temperature'
    long_name = 'Temperature at the Surface'
    units = 'K'
    units_alt = 'degC'
    type = 'sfc_met'
  [flds.ua]
    standard_name = 'eastward_wind'
    long_name = 'Eastward Wind'
    units = 'm s-1'
    units_alt = 'm s-1'
    type = 'pl_met'
  [flds.uas]
    standard_name = 'eastward_wind'
    long_name = 'Eastward Wind at 10 m'
    units = 'm s-1'
    units_alt = 'm s-1'
    type = 'sfc_met'
  [flds.va]
    standard_name = 'northward_wind'
    long_name = 'Northward Wind'
    units = 'm s-1'
    units_alt = 'm s-1'
    type = 'pl_met'
  [flds.vas]
    standard_name = 'northward_wind'
    long_name = 'Northward Wind at 10 m'
    units = 'm s-1'
    units_alt = 'm s-1'
    type = 'sfc_met'
  [flds.vorpot]
    standard_name = 'potential_vorticity_of_atmosphere_layer'
    long_name = 'Potential Vorticity'
    units = 'K m2 kg-1 s-1'
    units_alt = 'PVU'
    type = 'pl_dyn'
  [flds.wa]
    standard_name = 'upward_air_velocity'
    long_name = 'Vertical Velocity'
    units = 'm s-1'
    units_alt = 'm s-1'
    type = 'pl_met'
  [flds.wap]
    standard_name = 'lagrangian_tendency_of_air_pressure'
    long_name = 'Omega (vert. vel. in p coords, + downwards)'
    units = 'Pa s-1'
    units_alt = 'Pa s-1'
    type = 'pl_met'
  [flds.wsgmax10m]
    standard_name = 'wind_speed_of_gust'
    long_name = 'Maximum Wind Speed of Gust at 10m'
    units = 'm s-1'
    units_alt = 'm s-1'
    type = 'extreme'
  [flds.z0]
    standard_name = 'surface_roughness_length'
    long_name = 'Surface Roughness Length'
    units = 'm'
    units_alt = 'm'
    type = 'sfc_pbl'
  [flds.zg]
    standard_name = 'geopotential_height'
    long_name = 'Geopotential Height'
    units = 'm'
    units_alt = 'm'
    type = 'pl_met'
  [flds.zmla]
    standard_name = 'atmosphere_boundary_layer_thickness'
    long_name = 'Boundary Layer Height'
    units = 'm'
    units_alt = 'm'
    type = 'sfc_pbl'



 # [flds.]
 # standard_name = 'lookup CF'
 # long_name = ''
 # units = ''
 # units_alt = ''
 # type = ''


